### ISSUE TITLE
We don't have logical operators `&&` and `||`

### ISSUE THREAD

**Issue by antroseco** [DaveDuck321/GrapheneLang#65]
This should be a language feature instead of an overloadable function, as we really should have short-circuit evaluation

**Comment by antroseco** [comment]
What if these were keywords (`and`, `or`) instead to distinguish them from the overload-able operators?

**Comment by DaveDuck321** [comment]
Oh yeah, that's clean. 

We've already banned the overload of `&&` and `||` but this feels less arbitrary.
