### ISSUE TITLE
`sys_m{map, unmap}` have incorrect signatures

### ISSUE THREAD

**Issue by antroseco** [DaveDuck321/GrapheneLang#99]
https://pubs.opengroup.org/onlinepubs/009604499/functions/mmap.html
https://pubs.opengroup.org/onlinepubs/000095399/functions/munmap.html

First argument should be `iptr`, not `isize`.
`munmap` should also have a return type.

**Comment by idiotcommerce** [comment]
hi i want to work on this.  but small doubt. 

First argument should be iptr not isize.

don't take me wrong. i will show some images of code please help on that.

these are the functions you used as first argument as   ISIZE.  tell me where should i change.  not on this images 
very very sorry for that.

1  

![image](https://github.com/DaveDuck321/GrapheneLang/assets/121589808/d72216c7-e2e7-416a-8c7a-13d54fb7ee02)

2  

![image](https://github.com/DaveDuck321/GrapheneLang/assets/121589808/c825118a-d3b6-4cfe-a9bf-8d5045dfc837)

3

![image](https://github.com/DaveDuck321/GrapheneLang/assets/121589808/08ed8925-ce48-4198-98de-197042d09c25)

**Comment by antroseco** [comment]
Hi, and welcome to the project! I had already fixed this issue in one of the open PRs (https://github.com/DaveDuck321/GrapheneLang/pull/100/commits/20621de452b5d51454dc8784644f6f2f1214f7c0), but feel free to work on something else.

**Comment by idiotcommerce** [comment]
Ok ok
